server:
  port: 8083

spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    listener:
      simple:
        default-requeue-rejected: false

rabbitmq:
  exchange:
    order: order.exchange
  queue:
    notification: notification.queue.v2
    dlq: notification.dlq
  routing-key:
    order-confirmed: order.confirmed
    order-cancelled: order.cancelled
